// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// هذا التطبيق يدعم Android و iOS فقط.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are configured for Android and iOS only.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR1H_1u-Zilq_2LAmZgryVAKb3A6WnZ6I',
    appId: '1:247278142981:android:2b21a49302fe6cbadc3e6c',
    messagingSenderId: '247278142981',
    projectId: 'khatma-e1f43',
    storageBucket: 'khatma-e1f43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsrR9SHm6MQjjdQzInSwmnaeAZTLwx1yY',
    appId: '1:247278142981:ios:f6f2255559a9ddd8dc3e6c',
    messagingSenderId: '247278142981',
    projectId: 'khatma-e1f43',
    storageBucket: 'khatma-e1f43.firebasestorage.app',
    iosBundleId: 'com.hafedmih.khatma',
  );
}
